#!/bin/bash

if test -f /etc/default/jenkins-slave; then
	. /etc/default/jenkins-slave
else
	echo "Configuration for jenkins-slave does not exist" 1>&2
	exit 1
fi

# Get slave.jar from master
[ -n "${JENKINS_LOGIN}" ] && WGET_ARGS="--user=$JENKINS_LOGIN --password=$JENKINS_PASSWORD"
[ -f ${JENKINS_HOME}/slave.jar ] || wget --no-proxy $WGET_ARGS -O ${JENKINS_HOME}/slave.jar -q ${JENKINS_URL}/jnlpJars/slave.jar

java -jar ${JENKINS_HOME}/slave.jar ${JENKINS_ARGS}
